Revert "refactor: use lfs in flake"
This breaks some things in ways I cannot understand:

```
error:
       … while smudging git-lfs file '/users/bemeurer/assets/walls/plants-00.jpg'

       error: unable to upload 'https://git@github.com/lovesegfault/nix-config/info/lfs/objects/batch': HTTP error 403

       response body:

       Cookies must be enabled to use GitHub.
```

This reverts commit d98fde1fd86ea817361a151552091333849b6718.